import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { enableAutoUnmount, flushPromises, mount } from '@vue/test-utils'
import { nextTick } from 'vue'
import TownMailbox from './TownMailbox.vue'
import { deferred, letterFixture } from './social.fixtures'
import type { TownLetterInbox } from './social.types'

const api = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn() }))
vi.mock('../../../shared/api/client', () => ({ api }))
enableAutoUnmount(afterEach)

describe('TownMailbox', () => {
  beforeEach(() => {
    api.get.mockReset().mockResolvedValue({ letters: [], unreadCount: 0 })
    api.post.mockReset().mockResolvedValue(null)
  })

  it('has loading, empty, error and retry states and exposes refresh without any shell', async () => {
    const pending = deferred<TownLetterInbox>()
    api.get.mockReturnValueOnce(pending.promise)
    const wrapper = mount(TownMailbox)
    await nextTick()
    expect(wrapper.text()).toContain('正在整理信件')
    expect(wrapper.emitted('unread-change')).toBeUndefined()
    pending.reject(new Error('internal/private'))
    await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('暂时无法收取')
    expect(wrapper.text()).not.toContain('internal/private')
    await wrapper.get('[role="alert"] button').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('信箱还是空的')
    expect(wrapper.emitted('unread-change')).toEqual([[0]])
    await wrapper.vm.refresh()
    expect(api.get).toHaveBeenCalledTimes(3)
  })

  it('reads all three tracks locally, hides collapsed private bodies and never renders HTML', async () => {
    api.get.mockResolvedValue({ letters: [letterFixture('LONG', { body: '<img src=x onerror=alert(1)>私密信' }), letterFixture('NOTE'), letterFixture('INVITE')], unreadCount: 3 })
    const wrapper = mount(TownMailbox)
    await flushPromises()
    expect(wrapper.text()).not.toContain('私密信')
    const summaries = wrapper.findAll('.letter-summary')
    expect(summaries).toHaveLength(3)
    await summaries[0].trigger('click')
    await flushPromises()
    expect(wrapper.get('.letter-body').text()).toContain('<img src=x onerror=alert(1)>私密信')
    expect(wrapper.find('img').exists()).toBe(false)
    expect(wrapper.emitted('unread-change')?.at(-1)).toEqual([2])
    await summaries[0].trigger('click')
    expect(wrapper.find('.letter-body').exists()).toBe(false)
    await summaries[1].trigger('click')
    await flushPromises()
    expect(wrapper.get('.letter-body').text()).toContain('NOTE 的正文')
    await wrapper.get('[aria-label="信件分类"]').findAll('button')[3].trigger('click')
    expect(wrapper.findAll('.letter-summary')).toHaveLength(1)
    await wrapper.get('.letter-summary').trigger('click')
    await flushPromises()
    expect(wrapper.get('.letter-body').text()).toContain('INVITE 的正文')
    expect(wrapper.find('a').exists()).toBe(false)
    expect(api.post.mock.calls.map(call => call[0])).toEqual(['/town/letters/LONG/read', '/town/letters/NOTE/read', '/town/letters/INVITE/read'])
  })

  it('keeps a readable letter open on mark-read failure and retries without counting twice', async () => {
    api.get.mockResolvedValue({ letters: [letterFixture()], unreadCount: 1 })
    api.post.mockRejectedValueOnce(new Error('private'))
    const wrapper = mount(TownMailbox)
    await flushPromises()
    await wrapper.get('.letter-summary').trigger('click')
    await flushPromises()
    expect(wrapper.get('.letter-body').text()).toContain('LONG 的正文')
    expect(wrapper.text()).toContain('1 封未读')
    await wrapper.get('.letter-body button').trigger('click')
    await flushPromises()
    expect(wrapper.text()).toContain('0 封未读')
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
  })

  it('sends a private draft, retains failure, shows delayed delivery, then receives a next-day reply', async () => {
    const wrapper = mount(TownMailbox)
    await flushPromises()
    await wrapper.get('header button[aria-expanded]').trigger('click')
    expect(wrapper.get('textarea').attributes('maxlength')).toBe('2000')
    expect(wrapper.get('form button').attributes('disabled')).toBeDefined()
    await wrapper.get('textarea').setValue('今天想说的话')
    api.post.mockRejectedValueOnce(new Error('private'))
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(wrapper.get('textarea').element.value).toBe('今天想说的话')
    await wrapper.get('form').trigger('submit')
    await flushPromises()
    expect(wrapper.get('textarea').element.value).toBe('')
    expect(wrapper.text()).toContain('最早隔天')
    expect(wrapper.find('.letter-summary').exists()).toBe(false)
    api.get.mockResolvedValueOnce({ letters: [letterFixture('LONG', { deliverAt: '2026-09-07T08:00:00Z' })], unreadCount: 1 })
    await wrapper.vm.refresh()
    await flushPromises()
    await wrapper.get('.letter-summary').trigger('click')
    await flushPromises()
    expect(wrapper.get('.letter-body').text()).toContain('LONG 的正文')
  })

  it('reports track-specific empty states and clears draft on remount', async () => {
    const wrapper = mount(TownMailbox)
    await flushPromises()
    await wrapper.get('[aria-label="信件分类"]').findAll('button')[2].trigger('click')
    expect(wrapper.text()).toContain('还没有居民短笺')
    await wrapper.get('textarea').setValue('不应持久化')
    wrapper.unmount()
    const reopened = mount(TownMailbox)
    await flushPromises()
    expect(reopened.get('textarea').element.value).toBe('')
  })
})
