/** Generated by scripts/build-companion-assets.py. Every action has the same foot anchor. */
export const ACTION_FRAME = { width: 96, height: 96, originX: 32 / 96, originY: 80 / 96 }
export const RESIDENT_ART = [1, 3, 6, 9, 12] as const
export const RESIDENT_ACTIONS = {
  create: { frames: Array.from({ length: 14 }, (_, i) => i), frameRate: 5 },
  drink: { frames: Array.from({ length: 14 }, (_, i) => 14 + i), frameRate: 3 },
  // Lower the can after pouring; do not play the water stream backwards.
  garden: { frames: [...Array.from({ length: 14 }, (_, i) => 28 + i), 32, 31, 30, 29, 28, 28, 28], frameRate: 6 },
} as const
export function isArtAction(mode: string): mode is keyof typeof RESIDENT_ACTIONS {
  return Object.hasOwn(RESIDENT_ACTIONS, mode)
}
